appearance:
  name: Slack bot

receive:
  - name: WebSocket
    type: rtm
    token: xoxb-11771184720-rKdjOqL1Mffno6jJIztouAsa
    enabled: true

  - name: Outgoing WebHook
    type: webhook
    token: f5SrHXJr9xlp4BKb6aUnCetH
    enabled: true

  - name: Slash commands
    type: command
    token: khrsHR3MxEOag3StVVl665qe
    enabled: true

send:
  - name: WebSocket
    type: rtm
    token: xoxb-11771184720-rKdjOqL1Mffno6jJIztouAsa
    enabled: true

  - name: Incoming WebHook
    type: webhook
    url: https://hooks.slack.com/services/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
    enabled: true

  - name: Slack API
    type: api
    token: xoxb-11771184720-rKdjOqL1Mffno6jJIztouAsa
    enabled: true

log:
  path: var/slackbot.log
  level: 4

server:
  port: 8888
  pidfile: var/core.pid
  rtmpidfile: var/rtm.pid
